### ISSUE TITLE
editing sponsor content item gives an error on save

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.org#106]
example: https://plone.org/foundation/sponsorship/sponsors/maid2clean, make a change, save

```
Sorry, something went wrong with your request
Cannot read properties of undefined (reading 'title')

    at G (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2094277)
    at injectIntl(G)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at div
    at D (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:3821981)
    at r (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2809775)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at injectIntl(Connect(Connect(Component)))
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2347777)
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2348694)
    at main
    at div
    at m (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:308616)
    at H (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:3794867)
    at p (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2821372)
    at K (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:3798576)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at injectIntl(Connect(K))
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2347777)
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2348694)
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2347777)
    at C (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2083514)
    at https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2085708
    at n (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2349234)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at We (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:1764206)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:2344797)
    at n (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:3602306)
    at i (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:3603812)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at H (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:399667)
    at k (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:200821)
    at d (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:198551)
    at t (https://plone.org/static/js/client.b6dae0b1.chunk.js:2:3077156)
```

**Comment by ericof** [comment]
Issue still present after fix

**Comment by sneridagh** [comment]
@ericof it seems it's related to another issue, specifically when tries internal validation (not a server based one, but the basic that it's implemented in Volto itself, given the schema properties).

`Is a Plone provider` is the title of the field that is erroring, but it's clearly not, then when it tries to apply it to the schema to find the name of the field, it breaks since there is no such field title. It seems related to the `is_provider` field, does all this ring any bell?

**Comment by ericof** [comment]
@sneridagh Thanks!
That was it.

This is fixed in testing.plone.org, we should now deploy in live.

**Comment by ericof** [comment]
@tkimnguyen Deployed to live
