### ISSUE TITLE
error updating URL for a Foundation Sponsor

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.org#139]
https://plone.org/foundation/sponsorship/sponsors/sixfeetup if I edit it to change the URL of the sponsor's web site from http to https and save, 

```
Sorry, something went wrong with your request
Cannot read properties of undefined (reading 'title')

    at Y (https://plone.org/static/js/client.cade2484.chunk.js:2:1965246)
    at injectIntl(Y)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at div
    at N (https://plone.org/static/js/client.cade2484.chunk.js:2:3559610)
    at r (https://plone.org/static/js/client.cade2484.chunk.js:2:2349455)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at injectIntl(Connect(Connect(Component)))
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2221138)
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2222065)
    at main
    at div
    at m (https://plone.org/static/js/client.cade2484.chunk.js:2:155055)
    at I (https://plone.org/static/js/client.cade2484.chunk.js:2:3532412)
    at p (https://plone.org/static/js/client.cade2484.chunk.js:2:2362309)
    at Z (https://plone.org/static/js/client.cade2484.chunk.js:2:3536135)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at injectIntl(Connect(Z))
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2221138)
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2222065)
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2221138)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:1954666)
    at https://plone.org/static/js/client.cade2484.chunk.js:2:1956882
    at n (https://plone.org/static/js/client.cade2484.chunk.js:2:2222615)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at Ye (https://plone.org/static/js/client.cade2484.chunk.js:2:1634084)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2218120)
    at n (https://plone.org/static/js/client.cade2484.chunk.js:2:3336635)
    at i (https://plone.org/static/js/client.cade2484.chunk.js:2:3338141)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at I (https://plone.org/static/js/client.cade2484.chunk.js:2:246988)
    at k (https://plone.org/static/js/client.cade2484.chunk.js:2:45471)
    at d (https://plone.org/static/js/client.cade2484.chunk.js:2:43200)
    at t (https://plone.org/static/js/client.cade2484.chunk.js:2:2622247)
```

**Comment by tkimnguyen** [comment]
Getting the same or similar error trying to modify any values on an existing Foundation Sponsor item, e.g., https://plone.org/foundation/sponsorship/sponsors/webtide.

With https://plone.org/foundation/sponsorship/sponsors/design-intervention I got farther and was able to edit most of the values but get this error when I try to modify any dates in the Status or Dates field sets.
